<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Captured screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=errorAt12_18_.jpeg ><img src=errorAt12_18_.jpeg height=1280 width =720></a>]]>
    </line>
  </reporter-output>
  <suite started-at="2022-07-04T06:48:55Z" name="Data driver farmework" finished-at="2022-07-04T06:48:57Z" duration-ms="2519">
    <groups>
    </groups>
    <test started-at="2022-07-04T06:48:55Z" name="Login test" finished-at="2022-07-04T06:48:55Z" duration-ms="619">
      <class name="com.apoorv.testcases.BankManagerLoginTest">
        <test-method signature="loginAsBankManager()[pri:0, instance:com.apoorv.testcases.BankManagerLoginTest@740d2e78]" started-at="2022-07-04T06:48:55Z" name="loginAsBankManager" finished-at="2022-07-04T06:48:55Z" duration-ms="223" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[login not successful]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: login not successful
at org.testng.Assert.fail(Assert.java:96)
at com.apoorv.testcases.BankManagerLoginTest.loginAsBankManager(BankManagerLoginTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Captured screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=errorAt12_18_.jpeg ><img src=errorAt12_18_.jpeg height=1280 width =720></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- com.apoorv.testcases.BankManagerLoginTest -->
    </test> <!-- Login test -->
    <test started-at="2022-07-04T06:48:56Z" name="Add customer test" finished-at="2022-07-04T06:48:57Z" duration-ms="1465">
      <class name="com.apoorv.testcases.AddCustomerTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.apoorv.testcases.AddCustomerTest@34f22f9d]" started-at="2022-07-04T06:48:52Z" name="setUp" finished-at="2022-07-04T06:48:55Z" duration-ms="2490" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addCustomerTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.apoorv.testcases.AddCustomerTest@34f22f9d]" started-at="2022-07-04T06:48:57Z" name="addCustomerTest" data-provider="dp" finished-at="2022-07-04T06:48:57Z" duration-ms="528" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Raman]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Aruna]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[A234d]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.apoorv.testcases.AddCustomerTest@34f22f9d]" started-at="2022-07-04T06:48:57Z" name="TearDown" finished-at="2022-07-04T06:49:01Z" duration-ms="3364" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.apoorv.testcases.AddCustomerTest -->
    </test> <!-- Add customer test -->
  </suite> <!-- Data driver farmework -->
</testng-results>
